name: Compile All Scripts Test

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Run PyKotor's Compile Tests
      run: |
        git clone --branch vanilla-source-test https://github.com/th3w1zard1/PyKotor.git PyKotor
        cd PyKotor
        python -m pip install --upgrade pip
        ./install_python_venv.ps1 -noprompt
        python -m pip install -r ./Libraries/PyKotor/requirements.txt --prefer-binary
        python -m pip install -r ./Libraries/PyKotor/recommended.txt --prefer-binary
        python -m pip install pytest
        python -m pip install pytest pytest-html
        python -m pytest ./tests/resource/formats/pytest_ncs_compile_installation.py -v --full-trace -ra -o log_cli=true --junitxml=pytest_report.xml --html=pytest_report.html
      shell: pwsh

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()  # Ensures this step runs even if the previous step fails
      with:
        name: 'Pytest Results'  # Display name for the check run
        path: 'pytest_report.xml'  # Path to the JUnit XML report generated by pytest
        reporter: 'junit'  # Specifies the format of test results
        fail-on-error: true  # Optionally, you can fail the GitHub check if errors are found in test results
        # Customizes how many annotations are created from test results to avoid reaching GitHub's annotations limit
        max-annotations: 10

