name: Sync Fork's Master Branch with Upstream

on:
  schedule:
    - cron:  '0 */6 * * *' # Runs every 6 hours, adjust as needed
  workflow_dispatch: # Allows manual triggering of the action

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: master # Your branch to sync with upstream

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Sync with Upstream
        run: |
          git remote add upstream https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master